spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

# JWT
jwt:
  secret: VERY_VERY_SECRET_KEY_FOR_TIL_PROJECT_DONT_SHARE_THIS_KEY_WITH_ANYONE_BE_CAREFUL